"""sponsor_update_for_backmen

Revision ID: 17df4ce4b5ae
Revises: 37c7160a6a3a
Create Date: 2024-09-05 22:56:04.591631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17df4ce4b5ae'
down_revision: Union[str, None] = '37c7160a6a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('priority_join', sa.Boolean(), nullable=False))
    op.add_column('sponsors', sa.Column('loadouts', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('sponsors', sa.Column('open_all_roles', sa.Boolean(), nullable=False))
    op.add_column('sponsors', sa.Column('sponsor_chat', sa.Boolean(), nullable=False))
    op.drop_column('sponsors', 'have_priority_join')
    op.drop_column('sponsors', 'have_sponsor_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('have_sponsor_chat', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sponsors', sa.Column('have_priority_join', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('sponsors', 'sponsor_chat')
    op.drop_column('sponsors', 'open_all_roles')
    op.drop_column('sponsors', 'loadouts')
    op.drop_column('sponsors', 'priority_join')
    # ### end Alembic commands ###
