"""orientiks_cached_info

Revision ID: 3578151648d2
Revises: cc0096fbf325
Create Date: 2024-08-08 18:27:50.117331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3578151648d2'
down_revision: Union[str, None] = 'cc0096fbf325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orientiks_cached_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_sponsorship', sa.Integer(), nullable=False),
    sa.Column('total_friends', sa.Integer(), nullable=False),
    sa.Column('total_pardons', sa.Integer(), nullable=False),
    sa.Column('total_time_balancing', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('total_fine', sa.Integer(), nullable=False),
    sa.Column('total_from_time', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('orientiks', 'sponsorship',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orientiks', 'friends',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orientiks', 'pardons',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orientiks', 'time_balancing',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orientiks', 'spent',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orientiks', 'spent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orientiks', 'time_balancing',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orientiks', 'pardons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orientiks', 'friends',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orientiks', 'sponsorship',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('orientiks_cached_infos')
    # ### end Alembic commands ###
