"""seasons_upgrade

Revision ID: 707fa40b4586
Revises: eeb573a0f200
Create Date: 2024-08-01 14:28:44.469911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707fa40b4586'
down_revision: Union[str, None] = 'eeb573a0f200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seasons', 'awards',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seasons', 'awards',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               existing_nullable=False)
    # ### end Alembic commands ###
