"""sponsors_update

Revision ID: cc0096fbf325
Revises: 4afc89f1e066
Create Date: 2024-08-03 13:03:18.926665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc0096fbf325'
down_revision: Union[str, None] = '4afc89f1e066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsors', 'extra_slots',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sponsors', 'allowed_markings',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsors', 'allowed_markings',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('sponsors', 'extra_slots',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
