"""seasons

Revision ID: eeb573a0f200
Revises: 2e5ed9f756fd
Create Date: 2024-08-01 10:47:19.949795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb573a0f200'
down_revision: Union[str, None] = '2e5ed9f756fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('awards', sa.ARRAY(sa.JSON()), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('seasons_cached_playtime',
    sa.Column('cached_playtime_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('playtime', sa.Interval(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('cached_playtime_id')
    )
    op.alter_column('promotional_code_usages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotional_code_usages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('seasons_cached_playtime')
    op.drop_table('seasons')
    # ### end Alembic commands ###
